heat_template_version: 2014-10-16
description: 'Compute Post Deployment'
# NOTE: this is a noop for os-apply-config style deployments because
# post deployment ordering is controlled by tripleo-image-elements

parameters:
  servers:
    type: json

resources:


  # Note, this should come last, so use depends_on to ensure
  # this is created after any other resources.
  ExtraConfig:
    type: OS::TripleO::NodeExtraConfigPost
    properties:
        servers: {get_param: servers}

