heat_template_version: 2014-10-16

description: >
  Software Config to drive os-net-config with 2 bonded nics on a bridge.

resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          node_index: {get_input: node_index}
          network_config:
            -
              type: ovs_bridge
              name: {get_input: bridge_name}
              use_dhcp: true
              # Can't do this yet: https://bugs.launchpad.net/heat/+bug/1344284
              #ovs_extra:
              #  - list_join:
              #    - ' '
              #    - - br-set-external-id
              #      - {get_input: bridge_name}
              #      - bridge-id
              #      - {get_input: bridge_name}
              members:
                -
                  type: ovs_bond
                  name: bond1
                  use_dhcp: true
                  members:
                    # os-net-config translates nic1 => em1 (for example)
                    -
                      type: interface
                      name: nic1
                    -
                      type: interface
                      name: nic2

outputs:
  config_id:
    description: The ID of the OsNetConfigImpl resource.
    value:
      {get_resource: OsNetConfigImpl}
