heat_template_version: 2014-10-16
description: 'All Nodes Config for Puppet'

parameters:
  compute_hosts:
    type: comma_delimited_list
  controller_hosts:
    type: comma_delimited_list
  controller_ips:
    type: comma_delimited_list
  block_storage_hosts:
    type: comma_delimited_list
  object_storage_hosts:
    type: comma_delimited_list
  ceph_storage_hosts:
    type: comma_delimited_list
  controller_names:
    type: comma_delimited_list

resources:

  allNodesConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      config:
        completion-signal: {get_input: deploy_signal_id}
        hosts:
          list_join:
          - "\n"
          - - list_join:
              - "\n"
              - {get_param: compute_hosts}
            - list_join:
              - "\n"
              - {get_param: controller_hosts}
            - list_join:
              - "\n"
              - {get_param: block_storage_hosts}
            - list_join:
              - "\n"
              - {get_param: object_storage_hosts}
            - list_join:
              - "\n"
              - {get_param: ceph_storage_hosts}
        sysctl:
          net.ipv4.tcp_keepalive_time: 5
          net.ipv4.tcp_keepalive_probes: 5
          net.ipv4.tcp_keepalive_intvl: 1
        hiera:
          datafiles:
            all_nodes:
              mapped_data:
                controller_node_ips:
                  list_join:
                  - ','
                  - {get_param: controller_ips}
                rabbit_node_ips:
                  list_join:
                  - ','
                  - {get_param: controller_ips}
                mongo_node_ips:
                  list_join:
                  - ','
                  - {get_param: controller_ips}
                redis_node_ips:
                  list_join:
                  - ','
                  - {get_param: controller_ips}

outputs:
  config_id:
    description: The ID of the allNodesConfigImpl resource.
    value:
      {get_resource: allNodesConfigImpl}
