heat_template_version: 2014-10-16

description: >
  OpenStack ceph storage node post deployment for Puppet

parameters:
  servers:
    type: json

resources:
  CephStoragePuppetConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: puppet
      outputs:
      - name: result
      config:
        get_file: manifests/overcloud_cephstorage.pp

  CephStorageDeployment_Step1:
    type: OS::Heat::StructuredDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: CephStoragePuppetConfig}

  # Note, this should come last, so use depends_on to ensure
  # this is created after any other resources.
  ExtraConfig:
    depends_on: CephStorageDeployment_Step1
    type: OS::TripleO::NodeExtraConfigPost
    properties:
        servers: {get_param: servers}

